version: "3"

services:

  elasticsearch:
    build : ./elasticsearch
    restart: always
    expose:
      - 9200
      - 9300
    environment:
      - LOGSPOUT=ignore
      - "ES_JAVA_OPTS=-Xmx256m -Xms256m"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  logstash:
    build: ./logstash
    depends_on:
      - elasticsearch
    restart: always
    expose:
      - 5000
      - 9600
    environment:
      - LOGSPOUT=ignore
      - DROP_NON_JSON=false
      - "xpack.security.enabled=false"
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"

  logspout:
    build: ./logspout
    depends_on:
      - logstash
    restart: always
    expose:
      - 5000
    environment:
      - ROUTE_URIS=logstash://logstash:5000
      - LOGSTASH_TAGS=docker-elk
      - SYSLOG_FORMAT=rfc3164
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  kibana:
    build: ./kibana
    depends_on:
      - elasticsearch
    restart: always
    ports:
      - "5601:5601"
    environment:
      - LOGSPOUT=ignore
      - "xpack.security.enabled=false"

volumes:
  elasticsearch:
