FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4

# ENV LOGSPOUT=ignore
# ENV ES_JAVA_OPTS="-Xmx256m -Xms256m"

# EXPOSE 9200
# EXPOSE 9300

# VOLUME /usr/share/elasticsearch/data

# COPY ./config/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml
