FROM docker.elastic.co/logstash/logstash-oss:6.2.4

# ENV LOGSPOUT=ignore
# ENV DROP_NON_JSON=false
# ENV xpack.security.enabled=false
# ENV LS_JAVA_OPTS="-Xmx256m -Xms256m"

# EXPOSE 5000

# COPY ./config/logstash.yml /usr/share/logstash/config/logstash.yml
# COPY ./pipeline/* /usr/share/logstash/pipeline
