FROM gliderlabs/logspout:v3.2.5

# uses ONBUILD instructions described here:
# https://github.com/gliderlabs/logspout/tree/master/custom

# ONBUILD will copy build.sh and modules.go into the container for us
